//main
export const START_LOADING = 'MAIN/START_LOADING';
export const STOP_LOADING = 'MAIN/STOP_LOADING';
export const SHOW_SNACKBAR = 'MAIN/SHOW_SNACKBAR';
export const SET_REDIRECT_PATH = 'MAIN/SET_REDIRECT_PATH';

//nations
export const GET_NATIONS = 'NATION/GET_NATIONS';
export const GET_NATIONS_SUCCESS = 'NATION/GET_NATIONS_SUCCESS';
