//main
export const START_LOADING = 'MAIN/START_LOADING';
export const STOP_LOADING = 'MAIN/STOP_LOADING';
export const SHOW_SNACKBAR = 'MAIN/SHOW_SNACKBAR';
export const SET_REDIRECT_PATH = 'MAIN/SET_REDIRECT_PATH';

//nations
export const GET_NATIONS = 'NATION/GET_NATIONS';
export const GET_NATIONS_SUCCESS = 'NATION/GET_NATIONS_SUCCESS';
export const SET_SELECTED_NATION = 'NATION/SET_SELECTED_NATION';

//league
export const GET_LEAGUES = 'LEAGUE/GET_LEAGUES';
export const GET_LEAGUES_SUCCESS = 'LEAGUE/GET_LEAGUES_SUCCESS';
export const SET_SELECTED_LEAGUE = 'LEAGUE/SET_SELECTED_LEAGUE';

//club
export const GET_CLUBS = 'CLUB/GET_CLUBS';
export const GET_CLUBS_SUCCESS = 'CLUB/GET_CLUBS_SUCCESS';
export const SET_SELECTED_CLUB = 'CLUB/SET_SELECTED_CLUB';

//player
export const GET_PLAYERS = 'PLAYER/GET_PLAYERS';
export const GET_PLAYERS_SUCCESS = 'PLAYER/GET_PLAYERS_SUCCESS';
export const SET_SELECTED_PLAYER = 'PLAYER/SET_SELECTED_PLAYER';
